
  /postMo2men:
    get:
     summary: Get all postMo2mens
     tags: [postMo2men]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/postMo2men'
 
    post:
      summary: Create postMo2men
      tags: [postMo2men]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postMo2men'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postMo2men'
 
  /postMo2men/{id}:
    get:
      summary: Get postMo2men by id
      tags: [postMo2men]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postMo2men'
 
    put:
      summary: Edit postMo2men
      tags: [postMo2men]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postMo2men'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/postMo2men'
 
    delete:
      summary: Delete postMo2men
      tags: [postMo2men]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postMo2men'

  /user:
    get:
     summary: Get all users
     tags: [user]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/user'
 
    post:
      summary: Create user
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
  /user/{id}:
    get:
      summary: Get user by id
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
    put:
      summary: Edit user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
 
    delete:
      summary: Delete user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  components:
    schemas:
  
      postMo2men:
        type: object
        properties:
      
          id:
            type: string
          body:
            type: string
          title:
            type: string
      user:
        type: object
        properties:
      
          id:
            type: number
          name:
            type: string
          email:
            type: string
          gender:
            type: string
          age:
            type: number
          password:
            type: string